apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-flask-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: app-flask
  template:
    metadata:
      labels:
        app: app-flask
    spec:
      containers:
      - name: app-flask
        image: benjameto/my-flaks-app:latest  # Aimagen a construir
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-flask-service
spec:
  type: NodePort  # Si se usa en Minikube, NodePort es útil para acceder desde fuera del clúster
  selector:
    app: app-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008  
