apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-flask-deployment
  namespace: jenkins  # Flask y PostgreSQL estan en el mismo namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-flask
  template:
    metadata:
      labels:
        app: app-flask
    spec:
      containers:
      - name: app-flask
        image: benjameto/my-flaks-app:latest  # Imagen de Docker que contiene la aplicación Flask
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "postgres-service"  # El nombre del servicio de PostgreSQL en Kubernetes
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "hospitaldb"
        - name: DB_USER
          value: "hospitaluser"
        - name: DB_PASSWORD
          value: "hospitaluser1234"
---
apiVersion: v1
kind: Service
metadata:
  name: app-flask-service
  namespace: jenkins
spec:
  type: NodePort  # Para permitir acceso desde fuera del clúster
  selector:
    app: app-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008  # Puerto donde se expondrá Flask
